### ISSUE TITLE
Make homepage look decent 

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/smac-group.github.io#1]
URGENT - this is already online

Should look similar to http://publish.illinois.edu/stephane/ for example

**Comment by coatless** [comment]
Taken care of in commits:

9ff18d7e7325012376a0a565c24805e38196f2ea

1dfae28eb6abfc092f6280a4937e6b1d9356d6a6

b516e1a9ea4205b9329cfffc554c06f7fda67768

ff8084a3d9a034cdf7843e3ec998fdb363f53f25

b516e1a9ea4205b9329cfffc554c06f7fda67768

ff8084a3d9a034cdf7843e3ec998fdb363f53f25

c5b1443815b9b40dad90156cf2f563ca7ca02f4e

e272aa487e1d24245730e62edd575ee3c7bfdeee

Closing this out.
